data_root: ./data/downstream_task_data

tasks:

  FoldClassification:
    task_type: classification
    task_level: graph
    num_classes: 1195

    splits:
      train: training.txt
      val: validation.txt
      test:
        family: test_family.txt
        superfamily: test_superfamily.txt
        fold: test_fold.txt

    processed_dir: processed
    graph_dir: graphs

  ECReaction:
    task_type: classification
    task_level: graph
    num_classes: 384

    splits:
      train: training.txt
      val: validation.txt
      test: testing.txt

    processed_dir: processed
    graph_dir: graphs

  GeneOntology:
    task_type: multilabel_classification
    task_level: graph
    num_classes:
      MF: 489
      BP: 1943
      CC: 320

    splits:
      train: nrPDB-GO_train.txt
      val: nrPDB-GO_valid.txt
      test: nrPDB-GO_test.txt

    processed_dir: processed
    graph_dir: graphs

  BindingSite:
    task_type: node_classification
    task_level: node
    num_classes: 1

    splits:
      train: training.txt
      val: testing.txt

    processed_dir: processed
    graph_dir: graphs