# =========================================
# Data
# =========================================
data:
  pdb_dir: ./data/pretrain_data/01-benchmark_pdbs
  surface_dir: ./data/pretrain_data/01-benchmark_surfaces
  batch_size: 32

# =========================================
# Atom Encoder
# =========================================
atom:
  k: 8
  atom_feat_dim: 7
  hidden_dim: 256
  latent_dim: 128
  n_layers: 3
  lr: 0.001
  epochs: 50
  save_path: ./ckpts/atom_egnn_encoder.pt
  log_path: ./logs/training_log_atom_encoder.txt

# =========================================
# Surface Encoder
# =========================================
surface:
  input_dim: 16
  hidden_dim: 256
  latent_dim: 128
  n_layers: 3
  lr: 0.001
  max_faces: 1024
  epochs: 50
  save_path: ./ckpts/surface_emnn_encoder.pt
  log_path: ./logs/training_log_surface_encoder.txt

# =========================================
# Hierarchical GNN
# =========================================

hierarchical:
  hidden_dim: 128
  n_layers: 3
  dropout: 0.3

  # =========================================
  # WITH pretrained encoders (EGNN + EMNN)
  # =========================================
  input_dims:
    surface: 130    # EMNN output (128) + handcrafted (2)
    atom: 128       # EGNN output
    residue: 23     # one-hot + angles
    sse: 4          # type one-hot (3) + length (1)
    protein: 1280   # ESM-2 CLS token

  # =========================================
  # WITHOUT pretrained encoders (comment out above, uncomment below)
  # =========================================
  # input_dims:
  #   surface: 3      # face area + dist to center + bias
  #   atom: 7         # element one-hot (6) + backbone flag (1)
  #   residue: 23
  #   sse: 4     
  #   protein: 1280
  
# =========================================
# Output Heads
# =========================================

head:
  FoldClassification:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.3

  ECReaction:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.3

  GeneOntology:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.3

  BindingSite:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.3