# =========================================
# Data
# =========================================
data:
  pdb_dir: ./data/pretrain_data/01-benchmark_pdbs
  surface_dir: ./data/pretrain_data/01-benchmark_surfaces
  batch_size: 32

# =========================================
# Atom Encoder
# =========================================
atom:
  k: 8
  atom_feat_dim: 7
  hidden_dim: 256
  latent_dim: 128
  n_layers: 3
  lr: 0.001
  epochs: 50
  save_path: ./ckpts/atom_egnn_encoder.pt
  log_path: ./logs/training_log_atom_encoder.txt

# =========================================
# Surface Encoder
# =========================================
surface:
  input_dim: 16
  hidden_dim: 256
  latent_dim: 128
  n_layers: 3
  lr: 0.001
  max_faces: 1024
  epochs: 50
  save_path: ./ckpts/surface_emnn_encoder.pt
  log_path: ./logs/training_log_surface_encoder.txt

# =========================================
# Hierarchical GNN
# =========================================

hierarchical:
  hidden_dim: 128
  n_layers: 3
  dropout: 0.3
  input_dims:
    surface: 130    
    atom: 128       
    residue: 23     
    sse: 4          
    protein: 1280
  
# =========================================
# Output Heads
# =========================================

head:
  FoldClassification:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.3

  ECReaction:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.3

  GeneOntology:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.3

  BindingSite:
    hidden_dim: 128
    num_layers: 3
    dropout: 0.3